import { User, Event, Notification, Alumni } from "./types";

export const dummyEvents: Event[] = [
  {
    id: "event_001",
    title: "Guest Lecture: AI in Business",
    date: "2025-12-05",
    time: "6:00 PM - 8:00 PM",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop",
    description:
      "Learn how AI is transforming business operations and decision-making from industry leaders.",
    fullDescription:
      "Join us for an enlightening evening with leading AI practitioners from Fortune 500 companies. Discover how artificial intelligence is revolutionizing business processes, customer experiences, and strategic planning. This event features panel discussions, Q&A sessions, and networking opportunities.",
    location: "Wehner Building, Room 115",
    tags: ["guest_lecture", "ai", "technology"],
    isPast: false,
    agenda: [
      "6:00 PM - Welcome & Introductions",
      "6:15 PM - Keynote: AI Transformation in Enterprise",
      "7:00 PM - Panel Discussion",
      "7:30 PM - Q&A Session",
      "7:50 PM - Networking",
    ],
    speakers: [
      {
        name: "Dr. Michael Chen",
        title: "Chief AI Officer",
        company: "Microsoft",
      },
      {
        name: "Rebecca Martinez",
        title: "VP of Data Science",
        company: "Amazon Web Services",
      },
    ],
    attendees: [""],
  },
  {
    id: "event_002",
    title: "Case Competition Workshop",
    date: "2025-12-10",
    time: "5:00 PM - 7:00 PM",
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop",
    description:
      "Prepare for upcoming case competitions with expert coaching and practice sessions.",
    fullDescription:
      "Get ready to excel in case competitions! This intensive workshop covers case analysis frameworks, presentation skills, and team collaboration strategies. Past winners will share their experiences and provide personalized feedback on your approach.",
    location: "Mays Business School, Room 240",
    tags: ["case_competition", "workshop", "career_development"],
    isPast: false,
    agenda: [
      "5:00 PM - Workshop Introduction",
      "5:15 PM - Case Analysis Frameworks",
      "6:00 PM - Practice Case Session",
      "6:45 PM - Feedback & Tips",
    ],
    speakers: [
      {
        name: "James Wilson",
        title: "Strategy Consultant",
        company: "McKinsey & Company",
      },
    ],
    attendees: [""],
  },
  {
    id: "event_003",
    title: "Corporate Networking Night",
    date: "2025-12-12",
    time: "6:30 PM - 9:00 PM",
    image:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
    description:
      "Connect with recruiters and alumni from top companies in technology and consulting.",
    fullDescription:
      "An exclusive networking event featuring representatives from leading companies actively hiring CMIS graduates. Dress professionally and bring copies of your resume. This is your opportunity to make meaningful connections and learn about internship and full-time opportunities.",
    location: "Memorial Student Center, Ballroom",
    tags: ["networking", "career", "recruiting"],
    isPast: false,
    agenda: [
      "6:30 PM - Registration & Reception",
      "7:00 PM - Company Presentations",
      "7:45 PM - Speed Networking Sessions",
      "8:30 PM - Open Networking",
    ],
    speakers: [],
    attendees: [],
  },
  {
    id: "event_004",
    title: "CMIS Career Fair",
    date: "2025-12-15",
    time: "10:00 AM - 4:00 PM",
    image:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop",
    description:
      "Meet with 50+ companies looking to hire CMIS students for internships and full-time roles.",
    fullDescription:
      "The premier recruiting event for CMIS students! Over 50 companies from diverse industries will be on campus to meet you. Whether you're looking for internships, full-time positions, or just want to explore career options, this fair has something for everyone.",
    location: "Reed Arena",
    tags: ["career_fair", "recruiting", "networking"],
    isPast: false,
    agenda: [
      "10:00 AM - Fair Opens",
      "12:00 PM - Resume Review Sessions",
      "2:00 PM - Professional Headshots",
      "4:00 PM - Fair Closes",
    ],
    speakers: [],
    attendees: [],
  },
  {
    id: "event_005",
    title: "Aggie Data Science Symposium",
    date: "2025-11-18",
    time: "9:00 AM - 5:00 PM",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop",
    description:
      "A full-day symposium featuring the latest research and applications in data science.",
    fullDescription:
      "Already completed - this symposium showcased cutting-edge research in machine learning, big data analytics, and AI applications. Students and faculty presented their work and engaged with industry partners.",
    location: "Mays Business School",
    tags: ["data_science", "research", "symposium"],
    isPast: true,
    agenda: [],
    speakers: [],
    attendees: [""],
  },
  {
    id: "event_006",
    title: "Fall CMIS Welcome Reception",
    date: "2025-11-01",
    time: "5:00 PM - 7:00 PM",
    image:
      "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&auto=format&fit=crop",
    description:
      "Welcome reception for new CMIS students. Meet faculty, current students, and alumni.",
    fullDescription:
      "This past welcome reception brought together the CMIS community for an evening of networking and celebration. New students met faculty members, connected with peers, and learned about program opportunities.",
    location: "Wehner Building Atrium",
    tags: ["social", "networking", "welcome"],
    isPast: true,
    agenda: [],
    speakers: [],
    attendees: [""],
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: "notif_001",
    userId: "user_001",
    type: "event_reminder",
    title: "Event Tomorrow",
    message:
      "Guest Lecture: AI in Business starts tomorrow at 6:00 PM. See you there!",
    timestamp: "2025-12-04T09:00:00Z",
    read: false,
    actionUrl: "/events/event_001",
    actionText: "View Event",
    icon: "🔔",
  },
  {
    id: "notif_002",
    userId: "user_001",
    type: "event_registration",
    title: "Registration Confirmed",
    message:
      "You're registered for Case Competition Workshop on December 10th.",
    timestamp: "2025-11-20T14:20:00Z",
    read: false,
    actionUrl: "/events/event_002",
    actionText: "View Event",
    icon: "✅",
  },
  {
    id: "notif_003",
    userId: "user_001",
    type: "mentor_assigned",
    title: "Mentor Assigned",
    message:
      "Dr. Sarah Johnson from Deloitte Consulting is now your mentor. Reach out to schedule your first meeting!",
    timestamp: "2025-11-18T10:00:00Z",
    read: true,
    actionUrl: "/profile",
    actionText: "View Mentor",
    icon: "🎓",
  },
  {
    id: "notif_004",
    userId: "user_001",
    type: "event_reminder",
    title: "Event in 1 Hour",
    message:
      "Guest Lecture: AI in Business starts in 1 hour. Don't forget to attend!",
    timestamp: "2025-12-05T17:00:00Z",
    read: false,
    actionUrl: "/events/event_001",
    actionText: "View Event",
    icon: "⏰",
  },
  {
    id: "notif_005",
    userId: "user_001",
    type: "profile_reminder",
    title: "Update Your Profile",
    message:
      "Keep your profile up to date! Add more skills and interests to help us match you with opportunities.",
    timestamp: "2025-11-15T12:00:00Z",
    read: true,
    actionUrl: "/profile",
    actionText: "Update Profile",
    icon: "👤",
  },
  {
    id: "notif_006",
    userId: "user_001",
    type: "resume_reminder",
    title: "Resume Updated",
    message:
      "Your resume was successfully uploaded. Make sure it's current before the career fair!",
    timestamp: "2025-11-22T09:15:00Z",
    read: true,
    actionUrl: "/profile",
    actionText: "View Resume",
    icon: "📄",
  },
  {
    id: "notif_007",
    userId: "user_001",
    type: "event_registration",
    title: "You're Registered!",
    message:
      "Successfully registered for Guest Lecture: AI in Business on December 5th.",
    timestamp: "2025-11-25T16:45:00Z",
    read: true,
    actionUrl: "/events/event_001",
    actionText: "View Event",
    icon: "✅",
  },
];

export const dummyAlumni: Alumni[] = [
  {
    id: "alumni_001",
    name: "Sarah Chen",
    gradYear: 2018,
    role: "Senior Cloud Architect",
    company: "Amazon Web Services",
    headshot: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/08/Amazon-Web-Services-AWS-Logo.png",
    quote: "CMIS gave me the foundation to excel in cloud computing and enterprise architecture.",
    fullStory: "Sarah's journey in cloud computing began during her time at CMIS, where she discovered her passion for distributed systems and scalable architectures. After graduating in 2018, she joined AWS as a Solutions Architect and quickly rose through the ranks. Today, Sarah designs cloud infrastructure for Fortune 500 companies, helping them migrate to the cloud and optimize their operations. She credits CMIS's hands-on projects and industry connections for preparing her for the challenges of enterprise cloud consulting.",
    skills: ["AWS", "Cloud Architecture", "DevOps", "Kubernetes", "Terraform", "Python"],
    cmiActivities: ["Case Competition Winner", "CMIS Mixer Organizer", "Student Mentor"],
    timeline: [
      { year: 2018, title: "Graduated from CMIS", description: "Earned MS in Management Information Systems with focus on cloud computing" },
      { year: 2018, title: "Joined AWS as Solutions Architect", description: "Started in the public sector team, working with government clients" },
      { year: 2020, title: "Promoted to Senior Solutions Architect", description: "Expanded role to work with enterprise clients across industries" },
      { year: 2022, title: "Led Cloud Migration for Fortune 500", description: "Successfully migrated multi-billion dollar company to AWS cloud" },
      { year: 2024, title: "Current Role", description: "Leading cloud transformation initiatives for major enterprise clients" },
    ],
    industry: "Cloud",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/sarahchen",
  },
  {
    id: "alumni_002",
    name: "Michael Rodriguez",
    gradYear: 2019,
    role: "Cybersecurity Consultant",
    company: "Deloitte",
    headshot: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/08/Deloitte-Logo.png",
    quote: "The security courses at CMIS prepared me to protect organizations from emerging cyber threats.",
    fullStory: "Michael discovered his interest in cybersecurity during a security course at CMIS. After graduating in 2019, he joined Deloitte's cybersecurity practice and has since become an expert in penetration testing and security architecture. He has helped numerous organizations strengthen their security posture and respond to cyber incidents. Michael regularly speaks at security conferences and contributes to open-source security tools.",
    skills: ["Penetration Testing", "Security Architecture", "SIEM", "Incident Response", "Compliance", "Python"],
    cmiActivities: ["Cybersecurity Club Founder", "Guest Speaker", "Case Competition"],
    timeline: [
      { year: 2019, title: "Graduated from CMIS", description: "Specialized in information security and risk management" },
      { year: 2019, title: "Joined Deloitte Cybersecurity", description: "Started as a consultant focusing on security assessments" },
      { year: 2021, title: "Certified Ethical Hacker", description: "Obtained CEH and CISSP certifications" },
      { year: 2023, title: "Led Major Security Assessment", description: "Directed security audit for major financial institution" },
      { year: 2024, title: "Current Role", description: "Senior consultant leading enterprise security transformation projects" },
    ],
    industry: "Cybersecurity",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/michaelrodriguez",
  },
  {
    id: "alumni_003",
    name: "Jennifer Park",
    gradYear: 2020,
    role: "Data Analytics Manager",
    company: "Microsoft",
    headshot: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/02/Microsoft-Logo.png",
    quote: "CMIS taught me how to turn data into actionable business insights.",
    fullStory: "Jennifer's passion for data analytics was ignited during her CMIS capstone project, where she built a predictive model for customer churn. After graduating in 2020, she joined Microsoft's analytics team and has been instrumental in developing data-driven strategies. She now leads a team of analysts who transform complex data into insights that drive product decisions. Jennifer has published research papers on machine learning applications in business.",
    skills: ["SQL", "Python", "Tableau", "Machine Learning", "Power BI", "R", "Statistics"],
    cmiActivities: ["Data Analytics Club", "Research Assistant", "MIS Mixer"],
    timeline: [
      { year: 2020, title: "Graduated from CMIS", description: "Completed capstone on predictive analytics for customer retention" },
      { year: 2020, title: "Joined Microsoft as Data Analyst", description: "Started in the Office 365 analytics team" },
      { year: 2022, title: "Promoted to Senior Data Analyst", description: "Led analytics initiatives for Microsoft Teams product" },
      { year: 2023, title: "Became Analytics Manager", description: "Now managing a team of 8 data analysts" },
      { year: 2024, title: "Current Role", description: "Leading cross-functional analytics projects for Microsoft 365 suite" },
    ],
    industry: "Data Analytics",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/jenniferpark",
  },
  {
    id: "alumni_004",
    name: "David Kim",
    gradYear: 2017,
    role: "Product Manager",
    company: "Google",
    headshot: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/08/Google-Logo.png",
    quote: "The strategic thinking I developed at CMIS is essential in my product management role.",
    fullStory: "David combined his technical background from CMIS with a passion for user experience to transition into product management. After several years as a business analyst, he joined Google's Cloud Platform team as a Product Manager. He now oversees product strategy for developer tools and has launched several successful features that are used by millions of developers worldwide. David is known for his ability to bridge the gap between technical teams and business stakeholders.",
    skills: ["Product Strategy", "Agile", "User Research", "Data Analysis", "Stakeholder Management", "Go-to-Market"],
    cmiActivities: ["Product Management Club", "Case Competition", "Student Government"],
    timeline: [
      { year: 2017, title: "Graduated from CMIS", description: "Focused on business analysis and systems design" },
      { year: 2017, title: "Business Analyst at Accenture", description: "Worked on enterprise system implementations" },
      { year: 2019, title: "Product Owner Role", description: "Transitioned to product management at a startup" },
      { year: 2021, title: "Joined Google as PM", description: "Started on Google Cloud Platform team" },
      { year: 2024, title: "Current Role", description: "Leading product strategy for developer tools at Google Cloud" },
    ],
    industry: "Product Management",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/davidkim",
  },
  {
    id: "alumni_005",
    name: "Emily Johnson",
    gradYear: 2021,
    role: "Management Consultant",
    company: "McKinsey & Company",
    headshot: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/02/McKinsey-Logo.png",
    quote: "CMIS's case-based learning approach directly prepared me for consulting work.",
    fullStory: "Emily excelled in CMIS case competitions and found her calling in strategy consulting. After graduating in 2021, she joined McKinsey & Company and has worked on transformation projects for clients across industries. She specializes in digital transformation and has helped numerous companies modernize their technology infrastructure. Emily was promoted to Engagement Manager within three years and is now leading multi-million dollar transformation initiatives.",
    skills: ["Strategy Consulting", "Digital Transformation", "Process Improvement", "Change Management", "Financial Modeling", "Presentation"],
    cmiActivities: ["Case Competition Winner (x2)", "CMIS Mixer Organizer", "Consulting Club President"],
    timeline: [
      { year: 2021, title: "Graduated from CMIS", description: "Won multiple case competitions during program" },
      { year: 2021, title: "Joined McKinsey as Business Analyst", description: "Started in the digital practice" },
      { year: 2023, title: "Promoted to Associate", description: "Led workstreams on major transformation projects" },
      { year: 2024, title: "Promoted to Engagement Manager", description: "Now leading entire transformation engagements" },
      { year: 2024, title: "Current Role", description: "Managing digital transformation projects for Fortune 100 clients" },
    ],
    industry: "Consulting",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/emilyjohnson",
  },
  {
    id: "alumni_006",
    name: "Robert Thompson",
    gradYear: 2019,
    role: "Tech Lead",
    company: "Apple",
    headshot: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2020/04/Apple-Logo.png",
    quote: "The technical skills I gained at CMIS enabled me to build innovative products at Apple.",
    fullStory: "Robert's journey to Apple began with his passion for building impactful software. At CMIS, he worked on several projects that combined technical excellence with business value. After graduating in 2019, he joined Apple as a software engineer and quickly demonstrated leadership capabilities. He now leads a team building features for iOS and has contributed to several major product launches. Robert is passionate about mentoring new engineers and sharing his knowledge.",
    skills: ["Swift", "iOS Development", "Software Architecture", "Leadership", "Agile", "System Design"],
    cmiActivities: ["Software Development Club", "Hackathon Winner", "Teaching Assistant"],
    timeline: [
      { year: 2019, title: "Graduated from CMIS", description: "Focused on software engineering and systems architecture" },
      { year: 2019, title: "Software Engineer at Apple", description: "Joined the iOS team working on core features" },
      { year: 2021, title: "Senior Software Engineer", description: "Led development of new iOS features" },
      { year: 2023, title: "Promoted to Tech Lead", description: "Now leading a team of engineers" },
      { year: 2024, title: "Current Role", description: "Tech lead for iOS features used by millions of users" },
    ],
    industry: "Tech",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/robertthompson",
  },
  {
    id: "alumni_007",
    name: "Amanda Martinez",
    gradYear: 2020,
    role: "Investment Banking Analyst",
    company: "Goldman Sachs",
    headshot: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2020/09/Goldman-Sachs-Logo.png",
    quote: "CMIS gave me the analytical skills and business acumen to excel in finance.",
    fullStory: "Amanda discovered her interest in finance through CMIS courses that blended technology with business strategy. After graduating in 2020, she joined Goldman Sachs as an analyst in the technology, media, and telecom group. She has worked on several high-profile IPOs and M&A transactions, combining her technical background with financial expertise. Amanda has been promoted to Associate and continues to work on complex financial transactions.",
    skills: ["Financial Modeling", "Valuation", "M&A", "Excel", "PowerPoint", "Market Analysis"],
    cmiActivities: ["Finance Club", "Case Competition", "Student Investment Fund"],
    timeline: [
      { year: 2020, title: "Graduated from CMIS", description: "Combined technical and business coursework" },
      { year: 2020, title: "Investment Banking Analyst", description: "Joined Goldman Sachs TMT group" },
      { year: 2022, title: "Promoted to Associate", description: "Led workstreams on major transactions" },
      { year: 2024, title: "Current Role", description: "Working on strategic M&A transactions for tech companies" },
    ],
    industry: "Finance",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/amandamartinez",
  },
  {
    id: "alumni_008",
    name: "James Wilson",
    gradYear: 2018,
    role: "Energy Technology Manager",
    company: "ExxonMobil",
    headshot: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/02/ExxonMobil-Logo.png",
    quote: "CMIS prepared me to innovate at the intersection of technology and energy.",
    fullStory: "James combined his CMIS education with a passion for sustainable energy solutions. After graduating in 2018, he joined ExxonMobil's digital transformation team, where he applies data analytics and IoT technologies to optimize operations. He has led several initiatives that reduced energy consumption and improved safety through technology. James is now managing a team focused on deploying innovative technologies across operations.",
    skills: ["IoT", "Data Analytics", "Project Management", "Operations Technology", "SCADA", "Python"],
    cmiActivities: ["Energy Club", "Sustainability Project", "Industry Speaker"],
    timeline: [
      { year: 2018, title: "Graduated from CMIS", description: "Focused on enterprise systems and data analytics" },
      { year: 2018, title: "Technology Analyst at ExxonMobil", description: "Joined digital transformation team" },
      { year: 2020, title: "Led IoT Pilot Program", description: "Deployed IoT sensors for operational optimization" },
      { year: 2022, title: "Promoted to Manager", description: "Now managing technology initiatives" },
      { year: 2024, title: "Current Role", description: "Leading digital transformation projects across operations" },
    ],
    industry: "Energy",
    availableForMentorship: false,
    linkedInUrl: "https://linkedin.com/in/jameswilson",
  },
  {
    id: "alumni_009",
    name: "Lisa Anderson",
    gradYear: 2021,
    role: "Data Science Manager",
    company: "Netflix",
    headshot: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2020/04/Netflix-Logo.png",
    quote: "The data science projects at CMIS directly prepared me for my role at Netflix.",
    fullStory: "Lisa's expertise in data science was developed through rigorous coursework and projects at CMIS. After graduating in 2021, she joined Netflix's data science team, where she builds models that power recommendation systems and content strategy. She has worked on algorithms that improve user experience for millions of subscribers. Lisa was recently promoted to manager and now leads a team of data scientists.",
    skills: ["Machine Learning", "Python", "Big Data", "A/B Testing", "Statistical Modeling", "Spark"],
    cmiActivities: ["Data Science Club", "Research Projects", "Hackathon"],
    timeline: [
      { year: 2021, title: "Graduated from CMIS", description: "Specialized in data science and machine learning" },
      { year: 2021, title: "Data Scientist at Netflix", description: "Joined recommendation systems team" },
      { year: 2023, title: "Senior Data Scientist", description: "Led development of new recommendation algorithms" },
      { year: 2024, title: "Promoted to Manager", description: "Now managing team of data scientists" },
      { year: 2024, title: "Current Role", description: "Leading data science initiatives for content strategy" },
    ],
    industry: "Data Analytics",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/lisaanderson",
  },
  {
    id: "alumni_010",
    name: "Christopher Lee",
    gradYear: 2022,
    role: "Cybersecurity Engineer",
    company: "CrowdStrike",
    headshot: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop",
    companyLogo: "https://logos-world.net/wp-content/uploads/2021/06/CrowdStrike-Logo.png",
    quote: "CMIS's cybersecurity curriculum gave me the skills to protect organizations from threats.",
    fullStory: "Christopher focused on cybersecurity throughout his CMIS program, participating in security competitions and research projects. After graduating in 2022, he joined CrowdStrike, a leading cybersecurity company, as a security engineer. He works on developing threat detection systems and has contributed to several product innovations. Christopher is passionate about staying ahead of emerging threats and helping organizations defend against cyber attacks.",
    skills: ["Threat Detection", "Malware Analysis", "SIEM", "Incident Response", "Python", "Security Research"],
    cmiActivities: ["Cybersecurity Club", "Security Research", "Bug Bounty Programs"],
    timeline: [
      { year: 2022, title: "Graduated from CMIS", description: "Specialized in cybersecurity and threat intelligence" },
      { year: 2022, title: "Security Engineer at CrowdStrike", description: "Joined threat detection team" },
      { year: 2023, title: "Developed New Detection Algorithm", description: "Created innovative threat detection method" },
      { year: 2024, title: "Current Role", description: "Engineering advanced security solutions for enterprise clients" },
    ],
    industry: "Cybersecurity",
    availableForMentorship: true,
    linkedInUrl: "https://linkedin.com/in/christopherlee",
  },
];
